export const menus = [
  {
    createdAt: '2020-08-28 10:09:26',
    updatedAt: '2021-12-08 14:51:06',
    id: 1,
    parentId: null,
    name: '系统',
    router: '/sys',
    perms: null,
    type: 0,
    icon: 'icon-shezhi',
    orderNum: 255,
    viewPath: null,
    keepalive: true,
    isShow: true,
    isExt: false,
    openMode: 1,
  },
  {
    createdAt: '2020-08-01 00:00:00',
    updatedAt: '2021-12-08 14:52:50',
    id: 3,
    parentId: 1,
    name: '权限管理',
    router: '/sys/permssion',
    perms: null,
    type: 0,
    icon: 'icon-quanxian',
    orderNum: 0,
    viewPath: '',
    keepalive: true,
    isShow: true,
    isExt: false,
    openMode: 1,
  },
  {
    createdAt: '2020-08-08 00:00:00',
    updatedAt: '2021-12-08 14:53:35',
    id: 4,
    parentId: 3,
    name: '用户列表',
    router: '/sys/permssion/user',
    perms: null,
    type: 1,
    icon: 'icon-yonghu',
    orderNum: 0,
    viewPath: 'views/system/permission/user',
    keepalive: true,
    isShow: true,
    isExt: false,
    openMode: 1,
  },
]
